### ISSUE TITLE
PETSc Register Problem

### ISSUE THREAD

**Issue by MrOpine** [blechta/fenapack#10]
I used PyCharm to install the PETSc & Py4PETSc pkgs. It seems something wrong with the register status when running demos. What should I do?

Here is the log:

/usr/bin/python3 /home/opine/download/demo_navier-stokes-pcd.py
Traceback (most recent call last):
  File "/home/opine/download/demo_navier-stokes-pcd.py", line 26, in <module>
from fenapack import PCDKrylovSolver
  File "/home/opine/.local/lib/python3.6/site-packages/fenapack/__init__.py", line 30, in <module>
    from petsc4py import PETSc
  File "/home/opine/.local/lib/python3.6/site-packages/petsc4py/PETSc.py", line 4, in <module>
    PETSc._initialize()
  File "PETSc/PETSc.pyx", line 441, in petsc4py.PETSc._initialize
  File "PETSc/PETSc.pyx", line 429, in petsc4py.PETSc.register
  File "PETSc/Object.pyx", line 265, in petsc4py.PETSc.PyPetscType_Register
ValueError: key: 0, cannot register: <class 'petsc4py.PETSc.DMLabel'>, already registered: None

**Comment by blechta** [comment]
Sounds like there is something wrong with your installation of PETSc/petsc4py and/or your (PyCharm) environment. The minimal working example is
```
python3 -c "from petsc4py import PETSc"
```
Do you have multiple (conflicting) installations of PETSc and/or petsc4py?

**Comment by MrOpine** [comment]
Thank u for replying. Tried 
`python3 -c "from petsc4py import PETSc"`
in terminal, but an error occur 'the module is not installed'.
Checked pip list and the packages(PETSc/PETSc4py, FEniCs & fenapack) not included.
I used PyCharm to run the codes. 
The environment was chosen as usr/bin/python3,
and all packages above are installed.

**Comment by blechta** [comment]
I am sorry that I cannot really help with installation of Python packages in PyCharm. I don't use PyCharm. Anyway, it seems that `from petsc4py import PETSc` does not run in your PyCharm as indicated by your original post. I guess you need to get petsc4py running in PyCharm...

**Comment by MrOpine** [comment]
Thank you all the same!
